### PR TITLE
Message handling fix

### LINKED ISSUE #443: backend crashs if record wasn't found
```
{"level":"info","message":{"ensName":"abcd.dev-user.dm3.eth","method":"WS CONNECT","socketId":"ajbjqPi0qRqiURHYAAAB"}}
{"level":"info","message":{"ensName":"0xbcd6de065fd7e889e3ec86aa2d2780d7553ab3cc.dev-addr.dm3.eth","method":"WS CONNECT","socketId":"WzXITkqmleXz_kZ5AAAD"}}
/Users/heikoburkhardt/repos/ens-mail/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);
                    ^

Error: response not found during CCIP fetch: Record not found (url="http://localhost:8081/{sender}/{data}", errorMessage="Record not found", code=SERVER_ERROR, version=providers/5.7.2)
    at Logger.makeError (/Users/heikoburkhardt/repos/ens-mail/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/Users/heikoburkhardt/repos/ens-mail/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at JsonRpcProvider.<anonymous> (/Users/heikoburkhardt/repos/ens-mail/node_modules/@ethersproject/providers/lib/base-provider.js:897:58)
    at step (/Users/heikoburkhardt/repos/ens-mail/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/Users/heikoburkhardt/repos/ens-mail/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/Users/heikoburkhardt/repos/ens-mail/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'response not found during CCIP fetch: Record not found',
  code: 'SERVER_ERROR',
  url: 'http://localhost:8081/{sender}/{data}',
  errorMessage: 'Record not found'
}
```

### LINKED ISSUE #444: contact is shown twice in contact list
Problem:
```
[ 
  {"0x8101b0729eb9708a344c820fce80f12a90a7c1fa.dev-addr.dm3.eth,0xbcd6de065fd7e889e3ec86aa2d2780d7553ab3cc.dev-addr.dm3.eth" => Array(2)},
  {"0xbcd6de065fd7e889e3ec86aa2d2780d7553ab3cc.dev-addr.dm3.eth,hans.dev-user.dm3.eth" => Array(1)}
]
```

### LINKED ISSUE #446: Storage is used unnecessarily often

### PR DESCRIPTION
**Pull request by hai-ko**
closes #446 
closes #444
closes #443

### CODE REVIEW

File: packages/lib/src/account/Account.ts [hunk 1]
```diff
@@ -198,21 +190,11 @@ export function getAccountDisplayName(
 }
 
 export async function addContact(
```
Comment (AlexNi245) [inline packages/lib/src/account/Account.ts:192]: I think you've to merge the latest pr becuause this function moved to FE

**Review by AlexNi245 — APPROVED** [review]
