### PR TITLE
fix: contact list

### LINKED ISSUE #429: Contact list contains duplicate entries
After changing the user name to ...dev-user.dm3.eth and refreshing the contact list contains duplicate entries and real ones are missing

### PR DESCRIPTION
**Pull request by hai-ko**
closes #429

### CODE REVIEW

File: packages/lib/src/account/Account.ts [hunk 1]
```diff
@@ -116,7 +117,9 @@ export async function getContacts(
             .map((conversationId) => conversationId.split(','))
             .map((ensNames) =>
                 normalizeEnsName(connection.account!.ensName) ===
-                normalizeEnsName(ensNames[0])
+                    normalizeEnsName(ensNames[0]) ||
```
Comment (AlexNi245) [inline packages/lib/src/account/Account.ts:120]: maybe this can be moved to a function to increase readability

**Review by AlexNi245 — CHANGES_REQUESTED** [review]
see comment

**Review by AlexNi245 — APPROVED** [review]
